# Generated by Django 5.0.2 on 2024-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_messate',
            name='message',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
